<?php

namespace TraceReplay\Services;

use Illuminate\Support\Facades\Http;
use TraceReplay\Services\Ai\AiDriverInterface;
use TraceReplay\Models\Trace;

class AiPromptService
{
    protected AiDriverInterface $driver;

    public function __construct(AiDriverInterface $driver)
    {
        $this->driver = $driver;
    }
    /**
     * Build a rich, structured debugging prompt from a failed trace.
     */
    public function generateFixPrompt(Trace $trace): string
    {
        $errorStep = $trace->error_step;

        if (! $errorStep) {
            return 'This trace completed successfully with no errors recorded. Nothing to debug.';
        }

        $steps = $trace->steps()->orderBy('step_order')->get();
        $app = config('app.name', 'Laravel');

        $prompt = "You are an expert Laravel/PHP engineer. Your task is to diagnose and fix a failed request.\n\n";
        $prompt .= "## Application Context\n";
        $prompt .= "- **App:** {$app}\n";
        $prompt .= "- **Trace ID:** `{$trace->id}`\n";
        $prompt .= "- **Trace Name:** {$trace->name}\n";
        $prompt .= '- **Total Duration:** '.number_format($trace->duration_ms ?? 0, 2)." ms\n";
        $prompt .= "- **Step Count:** {$steps->count()}\n";
        $prompt .= "- **Failed At:** Step #{$errorStep->step_order} — `{$errorStep->label}`\n";

        if ($trace->user_id) {
            $prompt .= "- **User ID:** {$trace->user_id}\n";
        }
        if ($trace->ip_address) {
            $prompt .= "- **IP Address:** {$trace->ip_address}\n";
        }
        $prompt .= "\n";

        $prompt .= "## Execution Timeline\n\n";
        foreach ($steps as $step) {
            $icon = match ($step->status) {
                'success' => '✅',
                'error' => '❌',
                'checkpoint' => '📍',
                default => '⏳',
            };
            $prompt .= "{$icon} **Step {$step->step_order}: {$step->label}**";
            $prompt .= " | {$step->duration_ms} ms";
            if ($step->db_query_count) {
                $prompt .= " | {$step->db_query_count} queries ({$step->db_query_time_ms} ms)";
            }
            $prompt .= "\n";

            if (! empty($step->request_payload)) {
                $prompt .= '   - **Input:** `'.substr(json_encode($step->request_payload), 0, 500)."`\n";
            }
            if (! empty($step->state_snapshot)) {
                $prompt .= '   - **State:** `'.substr(json_encode($step->state_snapshot), 0, 500)."`\n";
            }

            if ($step->id === $errorStep->id) {
                $prompt .= "\n### 🚨 Failure Point\n\n";
                $errorStr = is_array($step->error_reason) ? json_encode($step->error_reason, JSON_PRETTY_PRINT) : ($step->error_reason ?? 'No error details.');
                $prompt .= "```json\n{$errorStr}\n```\n\n";
            }
        }

        $prompt .= "## Your Task\n\n";
        $prompt .= "1. **Root Cause:** Analyse the timeline and identify why Step #{$errorStep->step_order} (`{$errorStep->label}`) failed.\n";
        $prompt .= "2. **Hypothesis:** State your best hypothesis about the underlying issue.\n";
        $prompt .= "3. **Fix:** Provide a concrete, minimal code fix (PHP/Laravel) or configuration change.\n";
        $prompt .= "4. **Prevention:** Suggest how to prevent this class of error in the future (tests, validation, guards).\n\n";
        $prompt .= "_Context generated by TraceReplay — https://github.com/iazaran/trace-replay_\n";

        return $prompt;
    }

    /**
     * Call the configured AI driver.
     */
    public function callAi(string $prompt): ?string
    {
        return $this->driver->complete($prompt);
    }
}
